- src: git+https://github.com/wikitops/ansible_epel
  version: "1.3"
  name: epel

- src: git+https://github.com/wikitops/ansible_nginx
  version: "1.2"
  name: nginx

- src: git+https://github.com/wikitops/ansible_pip
  version: "1.4"
  name: pip
